# Generated by Django 5.2.17 on 2026-09-26 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='INITIATED', max_length=16)),
                ('provider_reference', models.CharField(max_length=64, unique=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'), models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_idempotency_key'), models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('booking',), name='unique_success_payment_per_booking')],
            },
        ),
    ]
