# Generated by Django 5.2.17 on 2026-09-29 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0002_webhook_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_success_payment_per_booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_required',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the gateway captured money that the booking can no longer use (late success after cancel/fail, or a second successful charge).'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('refund_required', False), ('status', 'SUCCESS')), fields=('booking',), name='unique_success_payment_per_booking'),
        ),
    ]
